### ISSUE TITLE
Add more countries in the migration match

### ISSUE THREAD

**Issue by abernardi** [tryton-ar/party_ar#10]
When migrating the afip code of the country are missing several countries.

**Comment by lukio** [comment]
Great @abernardi !! Could you fix the same issue to account_invoice_ar? :)
https://github.com/tryton-ar/account_invoice_ar/issues/96

**Comment by abernardi** [comment]
I don't see the same problem in account_invoice_ar.
You mean the migration of 'account.invoice.export.license'?
