### ISSUE TITLE
ws padron a4 its not working

### ISSUE THREAD

**Issue by lukio** [tryton-ar/party_ar#14]
more information regarding:
https://groups.google.com/d/msg/pyafipws/exH4ez5aIj4/iN7KU5ocEQAJ

seems that we need to replace ws_padron_A4 by ws_padron_A5 or padronA10

**Comment by faviodutria** [comment]
Hi Lukio. Can you see about information for MONOTRIBUTO? Because when I have a party with a condiction "MONOTRIBUTE", AFIP´s boton give wrong the activity information.

Regards.

**Comment by lukio** [comment]
Hi @faviodutria, are u sure that the system is not posting to homologacion instead of production? Could you send a log of the server when pressing the button AFIP? Thanks!
